### ISSUE TITLE
Silence ggdark?

### ISSUE THREAD

**Issue by Ni-Ar** [nsgrantham/ggdark#6]
Hi,

thanks for creating such a cool `ggplot2` extension!

I'm currently using your package as
```R
dark_theme_bw() +
   theme(legend.position = c(0.25, 0.18), 
         legend.background = element_blank(),
         legend.title = element_blank(), 
         legend.text = element_text(size = 12),
         legend.key.size = unit(6, units = 'mm'),
         axis.text = element_text(colour = 'white'),
         axis.title.x = element_blank() )
```
and every now and then I get a message that says:

```
Inverted geom defaults of fill and color/colour.
To change them back, use invert_geom_defaults().
```

Is it possible NOT to print such message? Is there something like `verbose = FALSE` argument?

Thanks!

**Comment by nsgrantham** [comment]
Yes! Try `dark_mode(theme_bw(), verbose = FALSE)` in place of `dark_theme_bw()`, does that silence the message?

**Comment by Ni-Ar** [comment]
Oh cool! It did work indeed! Thanks!
